Version chks now a funciton in main script

diff --git a/src/flsdk.in b/src/flsdk.in
--- a/src/flsdk.in
+++ b/src/flsdk.in
@@ -53,12 +53,17 @@ FLWKEYI="$HOMEDIR/flwkey"
 FLWRAPI="$HOMEDIR/flwrap"
 LINSIMI="$HOMEDIR/linsim"
 
-# flsdk general use directories
+# general use directories and variables
 LOGD="$HOMEDIR/logs"
 MKRD="$HOMEDIR/mkrd"
 SRCD="$HOMEDIR/src"
 TMPD="$HOMEDIR/tmp"
 WIN32="$HOMEDIR/win32"
+VERLOG="$TMPD/ver.tmp"
+
+# unicode variables
+CHK=${C_G}✔${C_NC}
+NONE="✘"
 
 # make sure all directories exist
 mkdir -p "$HOMEDIR"/{win32,src,tmp,logs,mkrd}
@@ -67,9 +72,20 @@ mkdir -p "$COMPTEXTI" "$COMPTTYI" "$FLAMPI" "$FLDIGII" "$FLLOGI" "$FLMSGI" "$FLN
 
 # setup build arrays
 declare -a default_build_array=( 'build_header' 'git_check' 'get_version' \
-'configure_header' 'default_configure' 'default_make' 'default_install' \
+'configure_header' 'set_installd' 'default_configure' 'default_make' 'default_install' \
 'default_version' 'copy_build_logs' 'install_marker' 'change_ownership' \
 'clean_after_build' 'build_summary')
+
+# version check function array
+declare -a vc_array=('vc_header' 'vc_uscan' 'vc_inet' \
+'vc_sf' 'vc_message_header' 'vc_flamp' 'vc_fldigi' \
+'vc_flmsg' 'vc_flnet' 'vc_flrig' 'vc_flwkey' 'vc_flwrap' 'vc_results')
+
+# watch file array
+declare -a watch_array=( 'flamp-alpha-watch' 'flamp-watch' 'fldigi-alpha-watch' \
+'fllog-alpha-watch' 'fllog-watch' 'flmsg-alpha-watch' 'flmsg-wath' \
+'flnet-alpha-watch' 'flnet-watch' 'flrig-alpha-watch' 'flrig-watch' \
+'flwkey-alpha-watch' 'flwkey-watch' 'flwrap-alpha-watch' 'flwrap-watch')
 
 # setup foreground colours
 C_R='\033[01;31m'	# red
@@ -216,12 +232,13 @@ unset_options() {
 set +e
 set +o pipefail
 set +u
+unset INSTALLD
 }
 
 #--under development------------------------------------------------------------
 under_development() {
 
-dialog --backtitle "$BACKTITLE" --title "$UD" --msgbox "$UDMSG" 7 50
+dialog --clear --backtitle "$BACKTITLE" --title "$UD" --msgbox "$UDMSG" 7 50
 
 }
 
@@ -517,9 +534,8 @@ autoreconf -f -i
 echo ''
 }
 
-# default configure(s)----------------------------------------------------------
-default_configure() {
-STEP='Configure Phase'
+# setup the install directory---------------------------------------------------
+set_installd() {
 
 # set the install directory based on --enable-separate ( enabled by default )
 if [ "$SEPARATE" = "Yes" ]; then
@@ -527,6 +543,12 @@ if [ "$SEPARATE" = "Yes" ]; then
 else
 	INSTALLD="$HOMEDIR/$APP_NAME/install"
 fi
+
+}
+
+# default configure(s)----------------------------------------------------------
+default_configure() {
+STEP='Configure Phase'
 
 case "$APP_NAME" in
 	comptext|comptty|fldigi|flamp|fllog|flmsg|flnet|flrig|flwkey|flwrap|linsim)
@@ -621,8 +643,6 @@ echo "* Copied config.log, Makefile to: $INSTALLD"
 cp -u "$SRCD/$APP_NAME"/{config.log,Makefile} "$INSTALLD"
 }
 
-
-
 # install marker----------------------------------------------------------------
 install_marker() {
 STEP='Install Marker'
@@ -631,10 +651,12 @@ echo '-----------------------------------------------------'
 echo -e ${C_Y}" GENERATING MARKERS"${C_NC}
 echo '-----------------------------------------------------'
 echo ''
-echo '* Removed old marker'
+echo '* Removing old markear'
 rm -f "$INSTALLD/version.mkr" &>/dev/null
-echo '* Installed new version marker'
-echo $RELEASE > "$INSTALLD"/version.mkr
+rm -f "$MKRD/$APP_NAME-version.mkr" &>/dev/null
+echo '* Installing new version markers'
+echo $RELEASE > "$INSTALLD/$APP_NAME-version.mkr"
+echo $RELEASE > "$MKRD/$APP_NAME-version.mkr"
 }
 
 # change ownership--------------------------------------------------------------
@@ -686,6 +708,305 @@ read -p "Press [ Enter ] to continue.."
 
 }
 
+
+################################################################################
+#
+# VERSION FUNCTION
+#
+################################################################################
+
+# NOTE: Where possible, all functions are in order of use to provide as much
+# clarity as possible / feasable
+
+# version check header----------------------------------------------------------
+version_check() {
+clear
+echo '-----------------------------'
+echo -e ${C_Y}'CHECKING VERSION INFORMATION'${C_NC}
+echo '-----------------------------'
+echo ''
+mkdir -p "$TMPD"
+rm -f "$VERLOG"
+
+# check for uscan
+uscan --version > /dev/null 2>&1 && echo -e "* Uscan ........ ${C_G}✔${C_NC}" || {
+	clear
+	echo ''
+	echo 'You must have *uscan* from the Debian devscripts'
+	echo 'package installed in order to perform version checks.'
+	echo ''
+	echo 'Due to the number of packages involed with devscripts,'
+	echo 'it is not installed as part of the default FLSDK install.'
+	echo 'As such, the installation is up to the user to perform.'
+	echo ''
+	echo 'There are many useful tools included with the package.'
+	echo 'It is highly advisable to install it. From a frsh distro'
+	echo 'stanpoint, total disk usage is only 3MB after install.'
+	echo ''
+	echo 'For Debian, Ubuntu and Mint, install with:'
+	echo ''
+	echo 'sudo apt-get devscripts'
+	echo ''
+	echo ''
+	continue
+	}
+
+# check Internet connectivity---------------------------------------------------
+((ping -w5 -c3 www.w1hkj.com || ping -w5 -c3 8.8.8.8 || ping -w5 -c3 208.67.222.222) > /dev/null 2>&1) && \
+	echo -e "* Internet ..... ${C_G}✔${C_NC}" || {
+	echo ''
+	echo -e ${C_R}'** INTERNET CONNECTION FAILURE**'${C_NC}
+	echo ''
+	echo 'You must have internet access inorder to'
+	echo 'perform version checks. The following'
+	echo 'test failed:'
+	echo ''
+	echo 'ping -w5 -c3 www.w1hkj.com || ping -w5 -c3 8.8.8.8 || ping -w5 -c3 208.67.222.222'
+	echo ''
+	echo 'FLDIG Website ...: www.w1hkj.com'
+	echo 'Google DNS ......: 8.8.8.8'
+	echo 'OpenDNS .........: 208.67.222.222'
+	echo ''
+	echo 'Check you can access the internet, resolve any connection'
+	echo "problems, then re-run Check Version"
+	echo ''
+	read -p "Press [ Enter ] to continue ..."
+	exit 1
+	}
+
+# check if we can access SourceForge repositories-------------------------------
+((git ls-remote git://git.code.sf.net/p/fldigi/fldigi HEAD) > /dev/null 2>&1) && \
+	echo -e "* Sourceforge .. ${C_G}✔${C_NC}" || {
+	echo ''
+	echo -e ${C_R}'** SOURCEFORGE CONNECTION FAILURE**'${C_NC}
+	echo ''
+	echo '@PROGRAM@ was unable to check the Git repository'
+	echo 'on Sourceforge. This may be a temporary fault or'
+	echo 'you may have internet connections issues.'
+	echo ''
+	echo 'If the problems presists, check that you can browse to the'
+	echo 'Git Repo on SF, and chek their Net Operations messages on'
+	echo 'on Twitter'
+	echo ''
+	read -p "Press [ Enter ] to continue ..."
+	exit 1
+	}
+
+# add message header to file----------------------------------------------------
+echo "APPLICATION RELEASE ALPHA LOCAL-BUILD" > "$VERLOG"
+echo '----------- ------- ----- -----------' >> "$VERLOG"
+
+
+# FLDIGI version check----------------------------------------------------------
+APP_NAME='fldigi'
+
+fldigi=$(uscan --watchfile @WATCHD@/fldigi-watch --package flmsg --upstream-version 0 --report |grep 'tar.gz')
+fldigi_release=$(echo ${fldigi##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{7}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/fldigi-alpha-watch --package fldigi --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	fldigia=$(uscan --watchfile @WATCHD@/fldigi-alpha-watch --package fldigi --upstream-version 0 --report |grep 'tar.gz')
+	fldigi_alpha=$(echo ${fldigia##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{7}//')
+else
+	fldigi_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLDIGI $fldigi_release $fldigi_alpha $buildv" >> "$VERLOG"
+echo -e "* FLDIGI ....... ${C_G}$CHK${C_NC}"
+
+
+# FLAMP version info------------------------------------------------------------
+APP_NAME='flamp'
+
+flamp=$(uscan --watchfile @WATCHD@/flamp-watch --package flmsg --upstream-version 0 --report |grep 'tar.gz')
+flamp_release=$(echo ${flamp##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flamp-alpha-watch --package flamp --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flampa=$(uscan --watchfile @WATCHD@/flamp-alpha-watch --package flamp --upstream-version 0 --report |grep 'tar.gz')
+	flamp_alpha=$(echo ${flampa##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	flamp_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLAMP $flamp_release $flamp_alpha $buildv" >> "$VERLOG"
+echo -e "* FLAMP ........ ${C_G}$CHK${C_NC}"
+
+
+# FLMSG version info------------------------------------------------------------
+APP_NAME='flmsg'
+
+flmsg=$(uscan --watchfile @WATCHD@/flmsg-watch --package flmsg --upstream-version 0 --report |grep 'tar.gz')
+flmsg_release=$(echo ${flmsg##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flmsg-alpha-watch --package flmsg --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flmsga=$(uscan --watchfile @WATCHD@/flmsg-alpha-watch --package flmsg --upstream-version 0 --report |grep 'tar.gz')
+	flmsg_alpha=$(echo ${flmsga##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	flmsg_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLMSG $flmsg_release $flmsg_alpha $buildv" >> "$VERLOG"
+echo -e "* FLMSG ........ ${C_G}$CHK${C_NC}"
+
+
+# FLRIG version info------------------------------------------------------------
+APP_NAME='flrig'
+
+flrig=$(uscan --watchfile @WATCHD@/flrig-watch --package flrig --upstream-version 0 --report |grep 'tar.gz')
+flrig_release=$(echo ${flrig##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flrig-alpha-watch --package flrig --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flriga=$(uscan --watchfile @WATCHD@/flrig-alpha-watch --package flrig --upstream-version 0 --report |grep 'tar.gz')
+	flrig_alpha=$(echo ${flriga##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	flrig_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLRIG $flrig_release $flrig_alpha $buildv" >> "$VERLOG"
+echo -e "* FLRIG ........ ${C_G}$CHK${C_NC}"
+
+
+# FLWKEY version info-----------------------------------------------------------
+APP_NAME='flwkey'
+
+flwkey=$(uscan --watchfile @WATCHD@/flwkey-watch --package flwkey --upstream-version 0 --report |grep 'tar.gz')
+flwkey_release=$(echo ${flwkey##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{7}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flwkey-alpha-watch --package flwkey --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flwkeya=$(uscan --watchfile @WATCHD@/flwkey-alpha-watch --package flwkey --upstream-version 0 --report |grep 'tar.gz')
+	flwkey_alpha=$(echo ${flwkeya##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{7}//')
+else
+	flwkey_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLWKEY $flwkey_release $flwkey_alpha $buildv" >> "$VERLOG"
+echo -e "* FLWKEY ....... ${C_G}$CHK${C_NC}"
+
+
+# FLWRAP version info-----------------------------------------------------------
+APP_NAME='flwrap'
+
+flwrap=$(uscan --watchfile @WATCHD@/flwrap-watch --package flwrap --upstream-version 0 --report |grep 'tar.gz')
+flwrap_release=$(echo ${flwrap##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{7}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flwrap-alpha-watch --package flwrap --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flwrapa=$(uscan --watchfile @WATCHD@/flwrap-alpha-watch --package flwrap --upstream-version 0 --report |grep 'tar.gz')
+	flwrap_alpha=$(echo ${flampa##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	flwrap_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLWRAP $flwrap_release $flwrap_alpha $buildv" >> "$VERLOG"
+echo -e "* FLWRAP ....... ${C_G}$CHK${C_NC}"
+
+
+# FLLOG version info -----------------------------------------------------------
+APP_NAME='fllog'
+
+fllog=$(uscan --watchfile @WATCHD@/fllog-watch --package fllog --upstream-version 0 --report |grep 'tar.gz')
+fllog_release=$(echo ${fllog##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/fllog-alpha-watch --package fllog --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flloga=$(uscan --watchfile @WATCHD@/fllog-alpha-watch --package fllog --upstream-version 0 --report |grep 'tar.gz')
+	fllog_alpha=$(echo ${flloga##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	fllog_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLLOG $fllog_release $fllog_alpha $buildv" >> "$VERLOG"
+echo -e "* FLLOG ........ ${C_G}$CHK${C_NC}"
+
+
+# FLNET version info -----------------------------------------------------------
+APP_NAME='flnet'
+
+flnet=$(uscan --watchfile @WATCHD@/flnet-watch --package flnet --upstream-version 0 --report |grep 'tar.gz')
+flnet_release=$(echo ${flnet##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+
+# Check Alpha builds
+if $(uscan --watchfile @WATCHD@/flnet-alpha-watch --package flnet --upstream-version 0 --report > /dev/null 2>&1) ; [[ "$?" == "0" ]]; then
+	flneta=$(uscan --watchfile flnet-alpha-watch --package flnet --upstream-version 0 --report |grep 'tar.gz')
+	flnet_alpha=$(echo ${flneta##*/} | sed -r 's/\.[[:alnum:]]+\.[[:alnum:]]+$//' |sed -r 's/^.{6}//')
+else
+	flnet_alpha="$NONE"
+fi
+
+# look for install mkr, set with the build script
+if [ -s "$MKRD/$APP_NAME-version.mkr" ] ; then
+	buildv=$(awk -F\| '{print $1}' < $MKRD/$APP_NAME-version.mkr)
+else
+	buildv="$NONE"
+fi
+
+echo "FLNET $flnet_release $flnet_alpha $buildv" >> "$VERLOG"
+echo -e "* FLNET ........ ${C_G}$CHK${C_NC}"
+
+# display version check results-------------------------------------------------
+echo ''
+cat "$VERLOG" |column -t
+echo ''
+echo -e "✘ - In ALPHA = A tar.gz file was not found at www.w1hkj.com"
+echo -e "✘ - In LOCAL-BUILD = You have not built the application"
+echo ''
+read -p "Press [ Enter ] to continue ..."
+
+}
+
 ################################################################################
 #
 # Start Main Script
@@ -713,7 +1034,7 @@ HELP="$DOCS/main_menu_help.txt"
 # MAIN MANU --------------------------------------------------------------------
 while [ 0 ]; do
 
-dialog --ok-label SELECT --nocancel --clear --backtitle "$BACKTITLE" --title \
+dialog --clear --ok-label SELECT --nocancel --clear --backtitle "$BACKTITLE" --title \
 "$MMTITLE" --menu "$MENUMSG" 19 62 20 --file "$TMPD/MMenu.tmp" 2> "$TMPD/selection"
 
 MMSELECT=$(head -c 1 < "$TMPD"/selection)
@@ -784,7 +1105,7 @@ elif [ "$MMSELECT" = "8" ]; then
 
 # Version Check-----------------------------------------------------------------
 elif [ "$MMSELECT" = "V" ]; then
-	flsdk-versions
+	version_check
 	continue
 
 # Help File---------------------------------------------------------------------
